controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


arm_controller:
  ros__parameters:

    joints:
      - shoulder_pan
      - shoulder_lift
      - elbow_flex
      - wrist_flex
      - wrist_roll
      - gripper_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: true

    constraints:
      stopped_velocity_tolerance: 0.05
      goal_time: 0.0

      shoulder_pan:
        trajectory: 0.2
        goal: 0.1

      shoulder_lift:
        trajectory: 0.2
        goal: 0.1

      elbow_flex:
        trajectory: 0.2
        goal: 0.1

      wrist_flex:
        trajectory: 0.2
        goal: 0.1

      wrist_roll:
        trajectory: 0.2
        goal: 0.1

      gripper_joint:
        trajectory: 0.2
        goal: 0.1
